bump

diff --git a/sbin/demon b/sbin/demon
--- a/sbin/demon
+++ b/sbin/demon
@@ -143,11 +143,30 @@ Listen()
             X 103
             ;;
         -H|--access|--httpd)
-            # if ! nc -z localhost 9006 >/dev/null 2>&1
-            # then
-            #     printf '%s\n' "Service not available."
-            #     X 100
-            # fi
+            # check if port is accessible
+            if ! nc -z localhost 80 >/dev/null 2>&1
+            then
+                printf '%s\n' "Cannot connect to port 80."
+                X 1
+            fi
+
+            # check if httpd is using that port
+            if ! lsof -i tcp:80 | grep httpd >/dev/null 2>&1
+            then
+                printf '%s' "Waiting for httpd ... "
+            fi
+
+            # if it is not using it, wait for it
+            (
+                while ! lsof -i tcp:80 | grep httpd >/dev/null 2>&1
+                do
+                    waited='yes'
+                    sleep 0.5
+                done
+                [[ $waited == 'yes' ]] && printf '%s\n\n' "ready."
+            ) &
+            wait
+
             nc localhost 9006
             X 103
             ;;
