making signaling more robust

diff --git a/sbin/http-byob b/sbin/http-byob
--- a/sbin/http-byob
+++ b/sbin/http-byob
@@ -5,10 +5,17 @@ unset CDPATH
 #set -x
 :
 Clean() {
-    rm "${HTTPD_PID}" >/dev/null 2>&1
-    rm "${DNSMASQ_PID}" >/dev/null 2>&1
-    ipconfig set en1 DHCP &
-    wait
+    if [[ $1 == '-H' || "${#1}" -eq 0 ]]
+    then
+        rm "${HTTPD_PID}" >/dev/null 2>&1
+    fi
+
+    if [[ $1 == '-D' || "${#1}" -eq 0 ]]
+    then
+        rm "${DNSMASQ_PID}" >/dev/null 2>&1
+    fi
+    # ipconfig set en1 DHCP &
+#     wait
     printf '%s\n' "Done cleaning."
 }
 
@@ -255,14 +262,23 @@ Restart()
 {
     if [[ $1 == '-H' || "${#1}" -eq 0 ]]
     then
+        [[ ! -r $HTTPD_PID  ]] &&  Msg "No httpd process found." && return
         pkill -HUP -F "${HTTPD_PID}" &
         printf '%s' "Restarting Apache httpd ... "
         wait
-        printf '%s (%s)\n' "done." "$?"
+        if ps -p "${HTTPD_PID}" >/dev/null 2>&1
+        then
+            printf '%s (%s)\n' "done." "$?"
+        else
+            printf '%s (%s)\n' "failed." "$?"
+            Clean -H
+            X 101
+        fi
     fi
 
     if [[ $1 == '-D' || "${#1}" -eq 0 ]]
     then
+        [[ ! -r "${DNSMASQ_PID}" ]] && Msg "No dnsmasq process found." && return
         Stop -D &
         wait
         Start -D
